### ISSUE TITLE
[Suggestion/Concept] "Fusion"-Tier Compressor

### ISSUE THREAD

**Issue by YoshiWoof22** [BearsDen989-GT/Gregtech-5u-Bears-Den-Edition#100]
To accompany the potential post-fusion expansion that might happen soon, I've decided to make a concept for a "fusion"-tier compressor. e99999 told me to go make it a suggestion/issue, so this is what im doing.
___
Name: "Neutronium Compressor"
Purpose: Endgame Compressor.
Basically combines the IV-Compressor and the Implosion Compressor into 1 single block.
Note: Adding the machine wouldnt require additional components to be added besides the machine and the recipe handler, as my suggested recipe uses components that are present and craftable in current GT5-BDE version.
___
Balancing:
-> The Neutronium Compressor replaces both the default compressor and the implosion compressor, unifies their recipes for simpler automation, and allows for near-instant processing times.
It uses "LuV"-EU/t. (= 32768 EU)
When processing implosion compressor recipes, it wont need TNT due to the power tier of the compressor.
-> Its in the late fusion age due to the recipe requiring a dense neutronium plate.
___
Part list:
```
1 Dense Neutronium Plate
2 Field Generators (IV)
2 Energy Flow Circuits
1 LuV Machine Hull
2 "1x" Superconductor Wires
1 Data Orb
```
Recipe Layout (output is placeholder):
![image](https://user-images.githubusercontent.com/31738147/47110271-a444f780-d250-11e8-96ec-82f05ea73524.png)

**Comment by e99999** [comment]
closing ideas, restricting to bugs
