### ISSUE TITLE
Power tool enhancements

### ISSUE THREAD

**Issue by diregarath** [BearsDen989-GT/Gregtech-5u-Bears-Den-Edition#11]
Power tools take no damage from proper use,
Also does not delete tool when durability = 0.

From @e99999

**Comment by bear989** [comment]
power tools should take damage but I say like a 10th of what a pickaxe or axe if used properly
so a steel pickaxe would last 10x less then a drill,

**Comment by xarses** [comment]
We'd probably want to scale the damage debuff with the material quality (tier) so we don't make HSS-E or something 10x stronger, maybe 4-6 times is good on that end (it already lasts foreverish) we also need to make sure that we don't apply the debuff to other things like turbine blades which we'd not want to modify

**Comment by e99999** [comment]
because higher end materials are not that hard to obtain in this version of gt5, I will probably leave the durability alone. and just focus on making tools stop working at durability == 0 instead of deleting so you can disassemble.

**Comment by e99999** [comment]
all power tools give empty hulls back that can be made back/upgraded into new tools.
