### ISSUE TITLE
covered pipes still burn

### ISSUE THREAD

**Issue by diregarath** [BearsDen989-GT/Gregtech-5u-Bears-Den-Edition#14]
from @bear989 was fixed in ,09 just needs ported back

**Comment by e99999** [comment]
we might be able to just merge https://github.com/Blood-Asp/GT5-Unofficial/commit/8e043d00d992040c7394a04797c2984847a19dd2#diff-348afe0c4eeda37bfbce1c5028387524 without much effort.

**Comment by diregarath** [comment]
e99999 I think that is the idea.  Thanks for linking the hash.  If we have other commits we can merge we should link their hashes too.  You working on this then?

**Comment by e99999** [comment]
fixed using .09 branch code
