### ISSUE TITLE
MV Motor Bug

### ISSUE THREAD

**Issue by CrazyJ1984** [BearsDen989-GT/Gregtech-5u-Bears-Den-Edition#23]
![2018-08-30_11 27 14](https://user-images.githubusercontent.com/29152096/44865739-c060eb00-ac48-11e8-8aea-80aa950c1cb2.png)
MV motor taking HV wires and cables

**Comment by e99999** [comment]
it looks like LV takes MV as well, then HV takes MV?? should I plan on fixing all three to proper tier?

**Comment by CrazyJ1984** [comment]
yes redo all to the proper tier

**Comment by e99999** [comment]
fixed, ported .09 recipes.
