### ISSUE TITLE
lapatrons from sapphires 

### ISSUE THREAD

**Issue by bear989** [BearsDen989-GT/Gregtech-5u-Bears-Den-Edition#27]
somewhat porting this up from GT4 and somewhat back porting from .09. the idea i have is use regular in place of the energy crystal, flawless uses good circuits rather than advanced, and a flawless would only need basics. I dont like the sapphire gem implosion compressor recipe that was added in .09 though, so you only get regular sapphires from dusts no doing regulars to get flawless and flawless to get exquisite, you take what you get of them from sifting only.

**Comment by e99999** [comment]
you want to give me whatever exact recipes you want and in what machine, and i can work on this?

**Comment by e99999** [comment]
lapatron with saphire instead of energy crystal
-1 tier circuit for flawless
-2 tier for esquisite

-from bear

**Comment by e99999** [comment]
added
