### ISSUE TITLE
Early game drain

### ISSUE THREAD

**Issue by diregarath** [BearsDen989-GT/Gregtech-5u-Bears-Den-Edition#3]
change recipe for the existing drain and add an advanced drain that functions closer to GT6 to the assembler

**Comment by diregarath** [comment]
Did you add an advanced drain already too?

**Comment by e99999** [comment]
no i can move it back to In progress.

**Comment by e99999** [comment]
more or less this is added and implemented, I'm gonna close it. All that's left for me to do is make it revert to normal crappy drain behavior when conditions are not met, but that means your also using it wrong so yeah not that important.
