### ISSUE TITLE
Stop Eating Cells

### ISSUE THREAD

**Issue by CrazyJ1984** [BearsDen989-GT/Gregtech-5u-Bears-Den-Edition#30]
Centrifuging air  to oxygen cell and nitrogen
![](https://cdn.discordapp.com/attachments/476873231991570432/487094717784522753/2018-09-05_23.00.13.png)

Electrolyzing green vitriol to nickel, oxygen cell, and sulfuric acid
![](https://cdn.discordapp.com/attachments/476873231991570432/487094797539082260/2018-09-05_23.00.35.png)

**Comment by e99999** [comment]
fixed no longer a hungry hippo for cells : )
