### ISSUE TITLE
Large Boiler efficiency was increased across the board.

### ISSUE THREAD

**Issue by bear989** [BearsDen989-GT/Gregtech-5u-Bears-Den-Edition#34]
https://ftb.gamepedia.com/Large_Boiler
Feed The Beast Wiki
Large Boiler
The Large Boiler is a multiblock structure added by GregTech 5 that burns enormous amounts of solid and liquid fuels to produce enormous amounts of Steam from Water.

Fuel Efficiency (5.09)
In GregTech 5 Unofficial Experimental version 5.09.00, Large Boiler efficiency was increased across the board.
this should be ported, the single blocks should not be better than the MBs

**Comment by e99999** [comment]
if anyone can find where this is implemented on 5.09 that would be awesome : ) i dont want to just go in blindly copying boiler code. or if anyone has other ideas on how to increase efficiency in a different way that would be awesome too.

**Comment by e99999** [comment]
"- It avoids dealing with so many transformers
- it avoids dealing with cable lines to chunkload
- it avoids dealing significant cable loss when you have meters of cables
- it avoids dealing with maintenance and worn-out rotors
- There is no rotor that output EV with Steam Turbine or when you have proper material to do so, there are better choices than Steam already
- Need to monitor Large Turbines becomes a impossible task when you have more than 2 Large Turbines
- Higher power tiers are always best served by Single-block Plasma or Naquadah"

-Leagris

**Comment by e99999** [comment]
closed until someone can tell me where this code is, sick of looking.
