### ISSUE TITLE
regulator seams broken

### ISSUE THREAD

**Issue by bear989** [BearsDen989-GT/Gregtech-5u-Bears-Den-Edition#35]
it is only moving one item not all here is a stream we played with it in if you need a bear report let me know
https://youtu.be/6rEc8b5S6S8

**Comment by e99999** [comment]
Bear was the broken one : )

**Comment by diregarath** [comment]
Well Sir @bear989 has a lot of special children - no wonder he is broken :)

**Comment by bear989** [comment]
have you seen the way to get it to work, it is as broken as me how is the 2 input slots of the chem reactor slots 4 & 5? and damn greg had a terrible interface in GT5

**Comment by diregarath** [comment]
I haven't seen how to get it to work.  Sounds messy.  slots 4 and 5?  lol

**Comment by bear989** [comment]
there are 3 3x3 grids, one is for the inputed items, the 2nd is where you set how many of each item goes out, and the 3rd is for you to set the slot number that each item goes into, and for some reason rather than it being slot 1 and 2 it is 4 and 5 for a chem reactor

**Comment by e99999** [comment]
Unfortunately nothing can be done about this, the regulator is basically a "developer tool" of sorts that pings the actual Gregtech code to determine slots and what not. Code side vs. what the player sees are very very different, and the amount of code to translate each machine to the 
"correct" slot  would be insurmountable.
