### ISSUE TITLE
void gases in wood tanks

### ISSUE THREAD

**Issue by e99999** [BearsDen989-GT/Gregtech-5u-Bears-Den-Edition#37]
from me to me 💯

**Comment by diregarath** [comment]
But wood likes to hold gases :)

**Comment by e99999** [comment]
yeah not that big deal of to me, you're not cheesing the game by putting 8 buckets worth of a gas into a wood tank... but I think its just more of a continuity thing for bear with wood pipes.

**Comment by diregarath** [comment]
I don't mind either way.    There is a reason wood tanks are not used in real life for much.

**Comment by e99999** [comment]
im adding it to my "do this when you get stuck on something else" list : )

**Comment by e99999** [comment]
fixed
