### ISSUE TITLE
Fix Ore Processing

### ISSUE THREAD

**Issue by diregarath** [BearsDen989-GT/Gregtech-5u-Bears-Den-Edition#4]
@bear989 Can you tell us what is broken here?

**Comment by bear989** [comment]
you should never get more from smelting a purified dust then you can get from fully processing it, IE malachite in all steps gives a few nuggets, put the purified dust will result in a full copper ingot. same with a lot of mixed metal ingots, elecrolyzer, centrifuge, or roasting should give the best output as it is at that step fully processed

**Comment by bear989** [comment]
![2018-08-28_06 33 40](https://user-images.githubusercontent.com/8433695/44717922-6b787580-aa8c-11e8-81f0-736cd9908871.png)
![2018-08-28_06 33 47](https://user-images.githubusercontent.com/8433695/44717925-6d423900-aa8c-11e8-8901-3a10e849a99b.png)
![2018-08-28_06 33 58](https://user-images.githubusercontent.com/8433695/44717929-6fa49300-aa8c-11e8-8a91-5904490ed18d.png)
![2018-08-28_06 34 02](https://user-images.githubusercontent.com/8433695/44717932-7206ed00-aa8c-11e8-9b2d-c64a31ef81e4.png)
![2018-08-28_06 34 08](https://user-images.githubusercontent.com/8433695/44717933-74694700-aa8c-11e8-905c-247f220f6dc1.png)
![2018-08-28_06 34 12](https://user-images.githubusercontent.com/8433695/44717937-76330a80-aa8c-11e8-931c-26198543c74d.png)

**Comment by bear989** [comment]
those values dont make sense. as it is now it is better to not process it at all or just crush-was-crush and cook, this should not be the case.

**Comment by e99999** [comment]
because this is something you could log on whenever you have spare time and teak values, would you be ok with me assigning this to you @diregarath ? and you can chip away at it whenever you get time?

**Comment by diregarath** [comment]
Sure that is fine.  Moving stinks. :)

**Comment by e99999** [comment]
should be fixed now 👍
