### ISSUE TITLE
new sulfuric acid electrolyzer recipe

### ISSUE THREAD

**Issue by bear989** [BearsDen989-GT/Gregtech-5u-Bears-Den-Edition#40]
![2018-09-16_12 34 56](https://user-images.githubusercontent.com/8433695/45598797-7c434980-b9af-11e8-9942-ee71552312cd.png)
same as this one except with sulfuric acid in the input tank, cells in the input slot for the hydrogen or oxygen, cells for the other. may need to add a program circuit but shouldnt.

**Comment by e99999** [comment]
added, revisit when we look how we want to restructure all cell intensive recipes.
