### ISSUE TITLE
Discussion: making Tin not a PITA

### ISSUE THREAD

**Issue by e99999** [BearsDen989-GT/Gregtech-5u-Bears-Den-Edition#46]
boosting tin you can get as ore byproducts without trying to increase oregen. ideas?

**Comment by e99999** [comment]
apparently if we use GTNH oregen, it fixes tin ore gen shit

**Comment by e99999** [comment]
#56

**Comment by bear989** [comment]
we still need to discuss the ore gen changes and someone needs to go into creative and make sure it isnt as OP as I have heard

**Comment by e99999** [comment]
moved to #56 @bear989
