### ISSUE TITLE
Experiment with NH Ore Gen

### ISSUE THREAD

**Issue by e99999** [BearsDen989-GT/Gregtech-5u-Bears-Den-Edition#56]
try experimenting in another branch with NH style Ore Gen, this would also fix asteroid generation.

**Comment by diregarath** [comment]
Haven't had a chance yet.  Stupid school starting and kids getting sick and making me sick.

**Comment by e99999** [comment]
```GregoriusTechneticies: its likely some block update causing it
GregoriusTechneticies: not the vein generator itself
NEW MESSAGES
OverBotBOTToday at 12:02 PM
GregoriusTechneticies: so small ores close to the chunk border cuase updates
GregoriusTechneticies: what ALSO results in runaway worldgen
GregoriusTechneticies: even if its just single chunk```

**Comment by e99999** [comment]
https://www.reddit.com/r/feedthebeast/comments/5x0twz/investigating_extreme_worldgen_lag/

very very very good post explaining cascading wordlgen issues with ore gen

**Comment by Muramasa-** [comment]
@e99999 Does the NH ore gen fix the cascading issues?

**Comment by e99999** [comment]
closing ideas, restricting to bugs
