### ISSUE TITLE
Item Barrels not counting items correctly

### ISSUE THREAD

**Issue by YoshiWoof22** [BearsDen989-GT/Gregtech-5u-Bears-Den-Edition#76]
Current item Barrels store items in "counts" of 2000 (So 2000, 4000, 8000, etc.).
To fit more with minecraft's counting system, they should store items in counts of stacks:
```
Wood = 2048 Items = 32 Stacks
Bronze = 4096 Items = 64 Stacks
Steel = 8192 Items = 128 Stacks
Titanium = 16384 Items = 256 Stacks
Tungstensteel = 32768 Items = 512 Stacks
```

**Comment by e99999** [comment]
this is how you make an issue 👍 🥇 , will be fixed in next push.
