### ISSUE TITLE
Make a trash can!

### ISSUE THREAD

**Issue by e99999** [BearsDen989-GT/Gregtech-5u-Bears-Den-Edition#77]
Placed in world: fluids and items instantly are voided, stuff can obviously be piped in or use the GUI.

Opened from hotbar: opens GUI, only voids items on closing the GUI.

**Comment by bear989** [comment]
anything not automated in should have a delay or button, safety for the
miss clicks

**Comment by e99999** [comment]
@bear989 not possible, would require two fluid inputs. one for the GUI and one for piping.

**Comment by bear989** [comment]
no no I am talking items how are you manually adding fluids?

**Comment by e99999** [comment]
closing ideas, restricting to bugs
