### ISSUE TITLE
Better idea: electric trash can

### ISSUE THREAD

**Issue by SuperCoder7979** [BearsDen989-GT/Gregtech-5u-Bears-Den-Edition#78]
As e99999 said, a trash can would be a very important addition to the mod. It would have many uses, such as destroying items, and making your friends cry by putting their life supply of iridium and aluminium in there. However, i think that an electric trashcan would be a better solution because then it would be more realistic. Independent research has shown that machines that take in EU are more efficient than machines that don't use electricity. the electric trash can will also include a paper shredder to remove those useless books you get from dungeon chests and if you want to troll your friends by shredding their prospection results. Anyways, an easy way to implement this feature is to obfuscate the mod, decompile it, and send someone underqualified to deobfuscate it, Most likely, this will result in an electric trash can that will work quickly and effectively. I hope you will take my advice and add electric trash cans. they will be very useful and very well received by the community.

**Comment by e99999** [comment]
+1 for an electric incinerator 👍

**Comment by e99999** [comment]
meh this basically a recycler that doesnt give you scrap right now. so would probably just make it a regular simple trash can.
