### ISSUE TITLE
Add portable tanks/drums and MB tanks like in GT6 

### ISSUE THREAD

**Issue by diregarath** [BearsDen989-GT/Gregtech-5u-Bears-Den-Edition#8]

**Comment by e99999** [comment]
this will be quite the undertaking. implementation is proposed in the follow major steps.

1. New Tank/Drum 
 - 32000L capacity 
 - 2000 degree heat limit, tank and contents will be deleted if liquid is too hot.

2. Upon wrenching the bottom side this new tank/tier of tanks will automatically
push fluids to adjacent pipes and machines.

3.Make these tanks, portable. Keeping liquid contents when harvested and placed.
 - Check compat with Railcraft multiblock fluid storage for possible crashes.

4.New multiblock liquid storage.

**Comment by bear989** [comment]
my opinion: 
new tank should be tier 1 and be wooden and only have 16000L capacity no gases
tier 2 should be steel and hold 32000L also should hold gases not just liquids
tier 3 should be titanium and be 64000L and if we are gonna do acidic non acidic fluids then this is the tier that can handle them
then tier 4 would be tungsten steel with 128000L 
all tiers should auto out to the bottom unless you want to do the wrench on and off thing like in GT6. also the heat capacity should be that of the material. 
optional tanks plastic for earlier gas, stainless steel for cheaper acidic(if that is gonna be a thing) both should be the same capacity as the tier they are taking the place of, ie wood/steel

**Comment by e99999** [comment]
initial release will probably include every feature outlined except portable tanks.
