### ISSUE TITLE
port in GT crops and bees

### ISSUE THREAD

**Issue by bear989** [BearsDen989-GT/Gregtech-5u-Bears-Den-Edition#83]
along with the nerf to them and a config option to un nerf for pussy mode. also add cinfig to turn all bees and crops added off.

**Comment by netmc** [comment]
I like the enhancement feature that GT 5.09 bees and plants have with giving you more of the purified ores by using the bee/plant products, but losing out on the byproducts that you normally get with processing the crushed into purified.  It's a nice option when you are taking the time to work with bees and/or crops.  This is by no means a replacement for straight mining. It's just a nice bonus if you take the time to get into the bees and plants.

**Comment by bear989** [comment]
net is one of if not the best bee person I have ever seen and with just mining I can out do his bee production of the materials to enhance with. so for a min/max player mining is the best way to go as doing bees or crops is slower than just going out and getting the ore and processing regularly. if Net and I worked together only a small portion of our ores would ever get the bee enhancement, most would still go threw regular processing

**Comment by e99999** [comment]
this is something I would like to discuss for a period of time before anyone attempts to shove all these crops and bees in this version. Aside from my complete and utter hatred for crops and bees, I'd like to stop looking to 5.09 for solutions and start thinking of our own. If we did anything different with crops/bees at all, i would prefer to come up with our own system.

**Comment by e99999** [comment]
closing ideas, restricting to bugs
