### ISSUE TITLE
scrap production

### ISSUE THREAD

**Issue by bear989** [BearsDen989-GT/Gregtech-5u-Bears-Den-Edition#84]
things that are actual elements give better chance of scrap, the idea is people look at breaking things down to elements rather than setting up more and more cheaty ways to use cobble, I also think RC walls and OB paths should be added to the blacklist to lessen the chance of cobble being used.  also cobble will give scrap but at say 100 or even 1000 per scrap for those that want to mine and keep there cobble. but the better way would be useless elements like sulfur, iron eventually, carbon, nickel things like that.

**Comment by netmc** [comment]
I would probably blacklist all walls, slabs, stairs, cobble, stone, sand, gravel (word match) automatically.

**Comment by e99999** [comment]
closing ideas, restricting to bugs
