### ISSUE TITLE
gregtech way to get to and from the end

### ISSUE THREAD

**Issue by bear989** [BearsDen989-GT/Gregtech-5u-Bears-Den-Edition#85]
there are so many things in GT that come from the end but it is the only dimension you cant enter and exit at or close to your base.

**Comment by leagris** [comment]
Do you want a recipe for end-portal frame using end materials?

**Comment by bear989** [comment]
well that is one idea yah, or a way to make a nether type portal if that is possible so you can come back without that damn end screen, but yes it should take end material so you cant make it without going there the vanialla way first,

**Comment by e99999** [comment]
closing ideas, restricting to bugs
