### ISSUE TITLE
Merge in Primitive blast furnace from .09 branch

### ISSUE THREAD

**Issue by diregarath** [BearsDen989-GT/Gregtech-5u-Bears-Den-Edition#9]
We want to use the primitive blast furnace blocks for a coke oven multiblock too.

**Comment by e99999** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/commit/6d151929908f5a8f30bc04aa0e4cced84e6fb5e5

**Comment by e99999** [comment]
merged from branch
